### ISSUE TITLE
Empty upstream/downstream consensus PAM sequences

### ISSUE THREAD

**Issue by ireneortega** [grybnicky/Spacer2PAM#1]
I used SPACER2PAM to determine the PAM sequences for a specific strain. However, the result of the function join2PAM give me the following dataframe [collectionFrame.txt](https://github.com/grybnicky/Spacer2PAM/files/10381834/collectionFrame.txt) in which no consensus PAM prediction is shown because the values for columns upPAM and downPAM are empty. What could happend?

**Comment by ireneortega** [comment]
I realized that the “Array.Orientation” column must be Forward or Reverse in order to determine the upstream and downstream consensus PAM sequences. Some of my “Array.Orientation” values are "ND" as CRISPRCasFinder reported, so I think I should replace those values with Forward or Reverse to get the consensus PAM sequences. SPACER2PAM worked well when I replaced them, then.

**Comment by ireneortega** [comment]
@grybnicky Do you think replacing ND by Forward is a valid approach? Or should I remove those CRISPR-Cas arrays with no orientation defined?

**Comment by grybnicky** [comment]
@ireneortega You are correct, "Array.Orientation" must contain a value of either "Forward" or "Reverse" in order to generate a prediction. If you do not know the direction of the spacers, I would recommend assigning an orientation such that all of the spacers with the same repeat are in the same direction. For example, if 2 arrays with the same repeat exist in opposite directions and you are unsure of the direction of transcription, I would assign one "Forward" and the other "Reverse" in order to have Spacer2PAM process them appropriately. Please note that if you arbitrarily assign the orientation in this manner, you should consider both the upstream and downstream predictions as possible PAMs (despite the known location for a specific system) since you might have assigned the incorrect orientation by random chance.

**Comment by ireneortega** [comment]
Okey, I understand your example, but in normal situations when I know the orientation of array, I don't know if I have to pay attention to the upstream or downstream prediction. Does upstream refers to the 5' end of the protospacer when the array is in the Forward orientation? So, for Reverse orientation, I should take the downstream prediction, right?

**Comment by grybnicky** [comment]
@ireneortega Regardless of orientation, upstream refers to the 5' from the protospacer and downstream refers to 3'. Spacer2PAM takes the orientation into account to make sure the PAM predictions are on the correct strand, so upstream is always 5' and downstream is always 3'.
